spring.profiles.active: dev 
# 集群中的结点（影响ID生成策略）
cluster.siteId: 1

management:
  security:
    enabled: false
    
spring:
  thymeleaf:
     prefix: classpath:/excel/
     suffix: .xls
  datasource:
     url: jdbc:mysql://47.98.177.211:3306/dys_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
     driver-class-name: com.mysql.jdbc.Driver
     username: root
     password: rd1234
     test-while-idle: true
     max-wait-millis: 30000
     validation-query: 'SELECT 1'
     time-between-eviction-runs-millis: 20000
     min-evictable-idle-time-millis: 28700
     
  jpa:
     database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
     hibernate.ddl-auto: update
     hibernate.show-sql: true
     
server:
  port: 8010
  contextPath: 
 
remain.login.times: 5  
  


















  